service: jackpot-number-detector
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - ses:SendEmail
      Resource: '*'

package:
  individually: true
  exclude:
    - ./** 
custom:
  environment:
    ACCOUND_ID: ${file(./env.yml):${self:provider.stage}.ACCOUND_ID}
    SENDER_EMAIL: ${file(./env.yml):${self:provider.stage}.SENDER_EMAIL}
    RECEIVER_EMAIL: ${file(./env.yml):${self:provider.stage}.RECEIVER_EMAIL}

functions:
  generateNumberTest:
    handler: index.handler
    timeout: 30 # 30 sec
    memorySize: 128
    events:
      - schedule: cron(0 15 ? * 6 *)  # Every friday at 73 UTC
    package:
      include: 
        - index.py  
        - utils/**
    environment:
      ACCOUND_ID: ${self:custom.environment.ACCOUND_ID}
      SENDER_EMAIL: ${self:custom.environment.SENDER_EMAIL}
      RECEIVER_EMAIL: ${self:custom.environment.RECEIVER_EMAIL}

plugins:
  - serverless-python-requirements